# Generated by Django 5.2.14 on 2026-09-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('STAFF', 'Staff'), ('PATIENT', 'Patient'), ('LAB_TECHNICIAN', 'Lab Technician')], db_index=True, default='PATIENT', max_length=15),
        ),
    ]
