# Generated by Django 4.2.7 on 2026-10-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_appointment_status_9fecd6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_status_9fecd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_appoint_8b74ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_doctor__4449b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_patient_6fe260_idx',
        ),
    ]
