# Generated by Django 5.2.14 on 2026-09-30 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Health Consultation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to='patients.patient')),
            ],
            options={
                'db_table': 'ai_chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('medications_data', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('doctor_review_required', models.BooleanField(default=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatsession')),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(db_index=True, max_length=255)),
                ('brand_names', models.JSONField(blank=True, default=list)),
                ('active_ingredients', models.JSONField(blank=True, default=list)),
                ('section', models.CharField(choices=[('INDICATIONS', 'Indications and Usage'), ('WARNINGS', 'Warnings and Precautions'), ('CONTRAINDICATIONS', 'Contraindications'), ('ADVERSE_REACTIONS', 'Adverse Reactions / Side Effects'), ('DRUG_INTERACTIONS', 'Drug Interactions'), ('DOSAGE_AND_ADMINISTRATION', 'Dosage and Administration'), ('PATIENT_INFORMATION', 'Patient Counseling Information'), ('GENERAL_SUMMARY', 'General Summary & Composition')], db_index=True, max_length=50)),
                ('section_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('CDSCO', 'CDSCO (Govt of India)'), ('DAILYMED', 'DailyMed (FDA SPL)'), ('OPENFDA', 'OpenFDA Drug Label'), ('MANUFACTURER', 'Manufacturer Monograph')], db_index=True, default='CDSCO', max_length=50)),
                ('source_url', models.URLField(max_length=500)),
                ('document_id', models.CharField(blank=True, max_length=100, null=True)),
                ('document_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=100, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medication Document',
                'verbose_name_plural': 'Medication Documents',
                'db_table': 'ai_medication_documents',
                'indexes': [models.Index(fields=['generic_name', 'section'], name='ai_medicati_generic_51d31f_idx'), models.Index(fields=['source', 'medication_name'], name='ai_medicati_source_3fbd94_idx')],
            },
        ),
    ]
