# Generated by Django 5.2.14 on 2026-10-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='clinical_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
